### PR TITLE
Add checks on `work` and `iwork`

### PR DESCRIPTION
**Pull request by jvdp1**
@wclodius2 Here are some additions for checks on `work` and `iwork`

### CODE REVIEW

**Review by wclodius2 — CHANGES_REQUESTED** [review]
Change "work array too small" to  "work array  is too  small". Technically in `stdlib_sorting_sort_index` `iwork` can be present independent of `work`, but you assume that `iwork` is present only if `work` is present. The `error stops` for `iwork` should be "iwork array is too small" not "work array too small".

**Comment by jvdp1** [comment]
> Change "work array too small" to "work array is too small". .... The `error stops` for `iwork` should be "iwork array is too small" not "work array too small".

Done.

> Technically in `stdlib_sorting_sort_index` `iwork` can be present independent of `work`, but you assume that `iwork` is present only if `work` is present.

I am not sure that I understand your comment. Here is the structure in `stdlib_sorting_sort_index`:

```fortran
! If necessary allocate buffers to serve as scratch memory.
        if ( present(work) ) then
            if ( size(work, kind=int_size) < array_size/2 ) then
                error stop "work array is too small."
            end if
            if ( present(iwork) ) then
                if ( size(iwork, kind=int_size) < array_size/2 ) then
                    error stop "iwork array is too small."
                endif
                call merge_sort( array, index, work, iwork )
            else
                allocate( ibuf(0:array_size/2-1), stat=stat )
                if ( stat /= 0 ) error stop "Allocation of index buffer failed."
                call merge_sort( array, index, work, ibuf )
            end if
        else
            allocate( buf(0:array_size/2-1), stat=stat )
            if ( stat /= 0 ) error stop "Allocation of array buffer failed."
            if ( present(iwork) ) then
                if ( size(iwork, kind=int_size) < array_size/2 ) then
                    error stop "iwork array is too small."
                endif
                call merge_sort( array, index, buf, iwork )
            else
                allocate( ibuf(0:array_size/2-1), stat=stat )
                if ( stat /= 0 ) error stop "Allocation of index buffer failed."
                call merge_sort( array, index, buf, ibuf )
            end if
        end if
```

This structure allows all possibilities: 
1) (present(work),present(iwork)), 
2) (present(work),.not.present(iwork)),
3) (.not.present(work), present(iwork)),
4) (.not.present(work), .not.present(iwork))

Or do I miss something?

**Comment by wclodius2** [comment]
You are right there is no assumption that `iwork` require `work`.

**Review by wclodius2 — APPROVED** [review]
Looks Good!

**Comment by jvdp1** [comment]
> Looks Good!

Thanks. From my side, you can merge it.

**Comment by wclodius2** [comment]
I think I have merged.

**Pull request merged**
